---
id: Pgp
name: Pgp
full: PGP library
description: A library for dealing with OpenPGP (RFC 4880) data.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/http: ^3
      horde/mime: ^3
      horde/stream: ^3
      horde/translation: ^3
      horde/url: ^3
      horde/util: ^3
    ext:
      hash: '*'
  optional:
    composer:
      horde/test: ^3
    ext:
      openssl: '*'
      zlib: '*'
